const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const root=path.resolve(__dirname,'../..');
function setup(seed={}){
 const records=new Map(Object.entries(seed)),elements=new Map();
 function element(){return {style:{},hidden:false,textContent:'',innerHTML:'',value:'',disabled:false,addEventListener(){},setAttribute(){},focus(){},remove(){},insertBefore(){},querySelector:()=>element(),querySelectorAll:()=>[],getTracks:()=>[]};}
 const get=s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s);};
 const context={window:{addEventListener(){}},document:{querySelector:get,querySelectorAll:()=>[],createElement:element,body:{appendChild(){}}},navigator:{},localStorage:{getItem:k=>records.get(k)||null,setItem:(k,v)=>records.set(k,v)},setTimeout:()=>1,clearTimeout(){},fetch:async()=>({ok:false,status:404}),location:{reload(){}},console,Date,Math,URL,Blob};
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'practice-data.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(root,'practice.js'),'utf8'),context);vm.runInContext('speakEn=()=>{}',context);return {run:s=>vm.runInContext(s,context),context,records,elements};
}
test('travel grading keeps accepting meaningful variants and rejecting the wrong requested item',()=>{const {run}=setup();assert.equal(run(`travelGrade({frame:TRAVEL_BY_ID.travel_can_i_get,ex:{en:'Can I get another towel?'}},'Can I get one more towel?').ok`),true);assert.equal(run(`travelGrade({frame:TRAVEL_BY_ID.travel_can_i_get,ex:{en:'Can I get another towel?'}},'Can I get a fork?').ok`),false);});
test('only selected travel expressions are sampled, with no unrelated learning modes',()=>{const {run}=setup();const ids=run(`travelBuildItems(10,[TRAVEL_FRAMES[0]]).map(it=>it.frame.id)`);assert.equal(new Set(ids).size,1);assert.equal(ids[0],run('TRAVEL_FRAMES[0].id'));for(const name of ['startAutoDrill','startVocab','openPhonics','rankOpen','startReactDrill','openSpeakHub','awardXP'])assert.equal(run(`typeof ${name}`),'undefined');});
test('wrong answers are saved and recur later, and three correct answers graduate the sentence',()=>{const {run}=setup();run(`startDrill(travelBuildItems(5,[TRAVEL_FRAMES[0]]),'여행 표현');autoDrillFinish('banana',{typed:true});`);assert.equal(run('autoDrill.items.length'),6);assert.equal(run('missList().length'),1);run(`const failed=autoDrill.items[0];missRecord(failed,true);missRecord(failed,true);missRecord(failed,true);`);assert.equal(run('missList().length'),0);});
test('revealed answers remain practice attempts and are scheduled again',()=>{const {run}=setup();run(`startDrill(travelBuildItems(5,[TRAVEL_FRAMES[0]]),'여행 표현');autoDrill.items[0]._hintUsed=true;autoDrillFinish(autoDrill.items[0].ex.en,{typed:true});`);assert.equal(run('autoDrill.results[0].ok'),true);assert.equal(run('autoDrill.results[0].perfect'),false);assert.equal(run('autoDrill.items.length'),6);});
test('existing travel, selection, and mistake records survive initialization',()=>{const old={'speakingroom:travelrepeat':JSON.stringify({travel_can_i_get:{ok:9,seen:9,introduced:true}}),'speakingroom:travel_study':JSON.stringify(['travel_can_i_get']),'speakingroom:travel_miss':JSON.stringify({'Can I get a towel?':{fid:'travel_can_i_get',miss:2,streak:0}}),'speakingroom:prof':JSON.stringify({xp:99})};const {records}=setup(old);for(const [k,v]of Object.entries(old))assert.equal(records.get(k),v);});
test('an AI reply arriving after leaving cannot replace the home or a new lesson',async()=>{const {run,context,elements}=setup();let resolve;context.delayed=new Promise(r=>resolve=r);run('callClaude=()=>delayed;state.scn=SURVIVAL[0];');const pending=run('startSession()');run('goToSetup()');resolve({content:[{type:'text',text:'Late reply'}]});await pending;assert.equal(run('curScreen'),'setup');assert.equal(run('state.busy'),false);assert.equal(run('state.convo.length'),0);assert.equal(elements.get('#threadInner').innerHTML,'');});
