const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const root=path.resolve(__dirname,'../..');
function setup(seed={}){
 const records=new Map(Object.entries(seed)),elements=new Map();
 function element(){return {style:{},hidden:false,textContent:'',innerHTML:'',value:'',disabled:false,addEventListener(){},setAttribute(){},focus(){},remove(){},insertBefore(){},querySelector:()=>element(),querySelectorAll:()=>[],getTracks:()=>[]};}
 const get=s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s);};
 const context={window:{addEventListener(){}},document:{querySelector:get,querySelectorAll:()=>[],createElement:element,body:{appendChild(){}}},navigator:{},localStorage:{getItem:k=>records.get(k)||null,setItem:(k,v)=>records.set(k,v)},setTimeout:()=>1,clearTimeout(){},fetch:async()=>({ok:false,status:404}),location:{reload(){}},console,Date,Math,URL,Blob};
 vm.createContext(context);for(const file of ['practice-data.js','practice.js','home-support.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context);vm.runInContext('speakEn=()=>{}',context);return {run:s=>vm.runInContext(s,context),context,records,elements};
}
test('restored home derives progress from actual records and keeps four practice modes',()=>{const {run,elements}=setup({'speakingroom:travelrepeat':JSON.stringify({travel_can_i_get:{seen:10,ok:8,streak:3}})});assert.equal(run('supportStats().accuracy'),80);assert.equal(run('supportStats().automatic'),1);assert.match(elements.get('#growthZone').innerHTML,/80%/);assert.match(elements.get('#routineZone').innerHTML,/기본표현/);assert.equal(run('typeof startVocab'),'undefined');});
test('practice drives daily goals and adaptive levels without XP rewards',()=>{const {run,records}=setup({'speakingroom:prof':JSON.stringify({xp:99})});run(`startDrill(travelBuildItems(5,[TRAVEL_FRAMES[0]]),'기본표현');autoDrillFinish(autoDrill.items[0].ex.en,{typed:true});`);assert.equal(run('supportToday().travel'),1);assert.equal(run('supportEvents().length'),1);assert.equal(run('supportStats().voice.length'),0);run(`for(let i=0;i<3;i++)autoLvlRecord('speak','perfect')`);assert.ok(run('alGet().speak')>1);assert.equal(JSON.parse(records.get('speakingroom:prof')).xp,99);});
test('snapshot merge preserves local learning and ignores auth and unrelated storage',()=>{const {run,records}=setup({'secret-token':'keep','speakingroom:travelrepeat':JSON.stringify({travel_can_i_get:{seen:10,ok:8,miss:2,lastT:200,streak:3}})});run(`supportApplySnapshot({'secret-token':'overwrite','speakingroom:travelrepeat':JSON.stringify({travel_can_i_get:{seen:3,ok:1,miss:2,lastT:100,streak:0}})});`);assert.equal(run('travelStat("travel_can_i_get").ok'),8);assert.equal(run('travelStat("travel_can_i_get").streak'),3);assert.equal(records.get('secret-token'),'keep');assert.equal(run('supportCollect()["secret-token"]'),undefined);});
test('sync retains historical server records but does not upload local secrets or conversations',async()=>{const {run,context}=setup({'secret-token':'private','speakingroom:travelrepeat':JSON.stringify({travel_can_i_get:{seen:2,ok:2}})});const calls=[];context.fetch=async(url,opts={})=>{calls.push({url,opts});return {ok:true,json:async()=>({d:{'speakingroom:old-vocab':'{"count":10}'},t:1})};};await run('supportSync("synthetic-test")');const body=JSON.parse(calls[1].opts.body);assert.equal(body.d['speakingroom:old-vocab'],'{"count":10}');assert.equal(body.d['secret-token'],undefined);assert.ok(body.d['speakingroom:travelrepeat']);assert.equal(calls.length,2);});
test('graduated mistakes cannot be reintroduced by an older device snapshot',()=>{const {run}=setup({'speakingroom:travelrepeat':JSON.stringify({travel_can_i_get:{seen:5,ok:4,streak:3,lastT:200}})});run(`supportApplySnapshot({'speakingroom:travel_miss':JSON.stringify({'Can I get a towel?':{fid:'travel_can_i_get',miss:1,streak:0,lastT:100}})});`);assert.equal(run('missCount()'),0);});
test('routine travel button opens selection without passing a click event as a question count',()=>{const {run,elements}=setup();run('let routineArgs=null;startTravelDrill=(...args)=>{routineArgs=args;};renderSupportHome();');elements.get('[data-routine="travel"]').onclick({type:'click'});assert.equal(run('routineArgs[0]'),10);assert.equal(run('routineArgs[1]'),true);assert.doesNotMatch(elements.get('#routineZone').innerHTML,/오답 다지기|실전회화/);assert.match(elements.get('#routineZone').innerHTML,/10회/);});
