const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'../..');
function setup(){
 const elements=new Map(),calls=[];const el=()=>({hidden:false,textContent:'',onclick:null,setAttribute(){}});
 const get=id=>{if(!elements.has(id))elements.set(id,el());return elements.get(id);};
 const context={window:{SpeakingRoomNative:{postMessage(raw){const m=JSON.parse(raw);calls.push(m);context.window.SpeakingRoomNative.onmessage({data:JSON.stringify({id:m.id,ok:true,result:{}})});}}},document:{getElementById:get},setTimeout:()=>1,clearTimeout(){},state:{scn:{},convo:[],busy:false},curScreen:'talk',TTS:{cancel(){}},svStop(){},stopMicrophone(){},rolePrompt:()=> 'scenario',stripUsedMarker:raw=>({clean:raw.split('⟦')[0]}),addMeTurn:t=>calls.push(['user',t]),addCoachTurn:(t,speak)=>calls.push(['assistant',t,speak]),setBusy:b=>{context.state.busy=b;},goToSetup(){context.curScreen='setup';context.state.scn=null;}};
 vm.runInNewContext(fs.readFileSync(path.join(root,'android-native.js'),'utf8'),context);return {context,elements,calls};
}
test('native voice updates the same conversation once without duplicate web speech',()=>{const {context,calls}=setup(),events=JSON.stringify([{id:1,kind:'user',text:'I ordered two slices.'},{id:2,kind:'assistant',raw:'Let me check.⟦USED:ordered⟧'}]);context.window.srNativeEvents(events);context.window.srNativeEvents(events);assert.equal(context.state.convo.length,2);assert.equal(calls.filter(c=>c[0]==='assistant').length,1);assert.equal(calls.find(c=>c[0]==='assistant')[2],false);});
test('help is displayed without becoming a learner answer or changing dialogue history',()=>{const {context,calls}=setup();context.window.srNativeEvents(JSON.stringify([{id:1,kind:'assistant',raw:'I ordered two slices.',help:true}]));assert.equal(context.state.convo.length,0);assert.equal(calls[0][1],'I ordered two slices.');});
test('late voice answers after returning home cannot enter another practice',()=>{const {context,calls}=setup();context.goToSetup();context.window.srNativeEvents(JSON.stringify([{id:1,kind:'user',text:'old answer'}]));assert.equal(context.state.convo.length,0);assert.equal(calls.length,0);});
test('voice begins only inside an existing AI dialogue',async()=>{const {context,elements,calls}=setup();await elements.get('nativeVoiceStart').onclick();assert.equal(calls.length,0);context.state.convo.push({role:'assistant',text:'Hello.'});await elements.get('nativeVoiceStart').onclick();const m=calls.find(c=>c.action==='voice');assert.deepEqual(m.data.history,[{role:'assistant',content:'Hello.'}]);assert.equal(context.state.busy,true);});
test('native AI provider never uses the hosted proxy',async()=>{const s=fs.readFileSync(path.join(root,'practice-data.js'),'utf8'),start=s.indexOf('async function callClaude('),end=s.indexOf('\n}',start)+2;const context={window:{SpeakingRoomNative:{},srNativeRequest:async(action,data)=>{assert.equal(action,'infer');assert.equal(data.instructions,'scenario');return {text:'Hello'};}},fetch:()=>{throw Error('Hosted proxy used');}};vm.runInNewContext(s.slice(start,end),context);assert.equal((await context.callClaude('scenario',[{role:'user',content:'Hi'}])).content[0].text,'Hello');});
